# These are supported funding model platforms

github: [coatless] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: coatless # Replace with a single Patreon username
buy_me_a_coffee: coatless # Replace with a single buymeacoffee username
thanks_dev: u/gh/coatless # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
